### ISSUE TITLE
feature_path in cbioportal_export missing in config

### ISSUE THREAD

**Issue by mbenary** [bihealth/snappy-pipeline#448]
**Describe the bug**
When running the wrapper cbioportal_export with RNAseq data, snappy throws an KeyError for path_features. "Path_features" is asked for in the init-file but not available in the config.

**To Reproduce**
1. Go to project DKTK_Master/pipeline_2023/cbioportal_export
2. Run snappy-snake -nrp

**Expected behavior**
Initializing snappy for cbioportal_export.

**Comment by mbenary** [comment]
Ignoring the gene expression step is not possible, I tested:
- Uncommenting `path_ngs_mapping`
- explicitly setting the `path_ngs_mapping` to ""

The error-code is the same, searching for the key `path_features`.

**Comment by ericblanc20** [comment]
The reason for the error is that the definition of features is also used to assign copy-number changes to individual genes. 

Using the `ngs_mapping` step 's configuration to obtain the path to the feature gtf is a very unfortunate choice, but at least it avoids different feature sets being used for expression and for CNV.

The proper way is probably to move the features to the `static_data_config` part. However, `STAR` indices can be created using a gtf file. I am not sure what happens when `STAR` is run with a gtf file and indices created with a different gtf.

**Comment by ericblanc20** [comment]
Just to make it clear: if you add the `path_features` entry in the config for `ngs_mapping`, the export should work. 

It won't work with expression, because the counts have not been generated. But at least you shouldn't be stuck.

**Comment by ericblanc20** [comment]
This is now fixed
